Edit double-press

diff --git a/scripts/double-press b/scripts/double-press
--- a/scripts/double-press
+++ b/scripts/double-press
@@ -17,21 +17,21 @@ unlocked() {
 	fi
 	
 # Options for the wofi menu
-OPTIONS="1. Scale display to 300%\n2. Scale display to 275%\n3. Scale display to 250%\n4. Scale display to 200%\n5. Scale display to 150%\n6. Scale-to-fit true\n7. Scale-to-fit false\n8. Close"
+OPTIONS="1. Take screenshot\n2. Take picture \n3. Scale display to 300%\n4. Scale display to 200%\n5. Scale display to 150%\n6. Scale-to-fit true\n7. Scale-to-fit false\n8. Close"
 
 # Display the menu and capture the user's selection
 SELECTION=$(echo -e "$OPTIONS" | wofi -d --prompt "Select an option:" --lines 8)
 
 # Execute a command based on the selection
 case "$SELECTION" in
-    "1. Scale display to 300%")
+    "1. Take screenshot")
+        take_screenshot
+        ;;
+    "2. Take picture")
+        take_picture
+        ;;
+    "3. Scale display to 300%")
         wlr-randr --output "HWCOMPOSER-1" --scale 3.00
-        ;;
-    "2. Scale display to 275%")
-        wlr-randr --output "HWCOMPOSER-1" --scale 2.75
-        ;;
-    "3. Scale display to 250%")
-        wlr-randr --output "HWCOMPOSER-1" --scale 2.50
         ;;
     "4. Scale display to 200%")
         wlr-randr --output "HWCOMPOSER-1" --scale 2.00
@@ -87,6 +87,51 @@ while read -r line; do
     fi
 done
 }
+
+take_picture() {
+    # Set up directory
+    HOME_DIR="$HOME"
+    PICTURES_DIR="$HOME_DIR/Pictures"
+    mkdir -p "$PICTURES_DIR"
+
+    # Get current date and time for filename
+    DATETIME=$(date +"photo_%Y%m%d_%H%M%S")
+    FILENAME="$PICTURES_DIR/$DATETIME.jpeg"
+
+    # Command to take picture
+    gst-launch-1.0 -e \
+      droidcamsrc camera-device=0 mode=2 ! \
+      videoconvert ! \
+      videoflip video-direction=8 ! \
+      jpegenc snapshot=true ! \
+      filesink location="$FILENAME"
+
+    # Notify user
+    if [ $? -eq 0 ]; then
+      echo "Picture saved to: $FILENAME"
+      command -v notify-send >/dev/null && notify-send "Picture Taken" "Saved to $FILENAME" --icon="/home/furios/.git/fastflx1/files/fastflx1.svg"
+    else
+      echo "Failed to take picture."
+    fi
+  fi
+}
+
+take_screenshot() {
+    SCREENSHOT_PATH="$(xdg-user-dir PICTURES)/Screenshot-$(date +%F-%T).png"
+    gdbus call --session --dest org.gnome.Shell.Screenshot \
+      --object-path /org/gnome/Shell/Screenshot \
+      --method org.gnome.Shell.Screenshot.Screenshot \
+      true false "$SCREENSHOT_PATH" &
+
+    # Notify user
+    if [ $? -eq 0 ]; then
+      echo "Screenshot saved to: $SCREENSHOT_PATH"
+      command -v notify-send >/dev/null && notify-send "Screenshot Taken" "Saved to $SCREENSHOT_PATH" --icon="/home/furios/.git/fastflx1/files/fastflx1.svg"
+    else
+      echo "Failed to take screenshot."
+    fi
+}
+
 
 # Identify the session ID
 session_id=$(loginctl list-sessions | grep $(whoami) | awk 'NR==2 {print $1}')
